### ISSUE TITLE
Controllers not inheriting methods from ApplicationController

### ISSUE THREAD

**Issue by evilstreak** [activeadmin/inherited_resources#69]
If I define a method on my ApplicationController and try to use it as a filter in a controller inheriting from InheritedResources::Base it produces an "undefined local variable or method 'my_filter'" error:

```
class ApplicationController < ActionController::Base
  def my_filter
    ...
  end
end

class ProductsController < InheritedResources::Base
  before_filter :my_filter
end
```

If I inherit directly from ApplicationController it works as expected which should rule out careless mis-naming errors on my part.

I am using rails 3.0.0.beta4 and inherited_resources 1.1.2

**Comment by josevalim** [comment]
InheritedResources::Base inherits from ApplicationController. That said, the scenario you just described works like a charm here. Which error are you getting?

**Comment by evilstreak** [comment]
The error I'm getting is:

```
NameError (undefined local variable or method `my_filter' for #<ProductsController:0x00000104fb9d48>)
```

There's also a [full stack trace](http://pastie.org/1101889) if that's useful. I should probably have mentioned already, I'm using Ruby 1.9.2.

**Comment by josevalim** [comment]
It should also work in Ruby 1.9.2:

http://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/base.rb#L14

Have you restarted the server and it still does not work?

**Comment by evilstreak** [comment]
Now I feel really stupid. Server restarted and it works like a charm. Apologies for wasting your time with this, and thanks for helping out.

**Comment by josevalim** [comment]
Actually, this is an issue. Server restart should not be required.
